apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport
  namespace: gangwon
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 8880
    targetPort: 8880
    nodePort: 30880